Asopalav/Controllers/ProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Asopalav.Helpers;
using Asopalav.Models;
using DataAccessLayer;

namespace Asopalav.Controllers
{
    public class ProductDetailsController : Controller
    {
        // GET: ProductDetails
        [Route("ProductDetails/{id}")]
        public ActionResult Index(string id)
        {
            var host = System.Web.HttpContext.Current.Request.Url.OriginalString.Replace(System.Web.HttpContext.Current.Request.Url.PathAndQuery, "");
            ProductDetailsModel objProductDetailsModel = new ProductDetailsModel();
            int counter = 0;
            using (var context = new AsopalavDBEntities())
            {
                var decodedId = int.Parse(id.Base64Decode());
                objProductDetailsModel.objProductMaster = context.ProductMasters.Include("Images").Where(p => p.ProductID == decodedId).FirstOrDefault();

                if ((string)Session["CurrentCurrency"] == "INR")
                {
                    objProductDetailsModel.objProductMaster.Price = Math.Round(objProductDetailsModel.objProductMaster.Price * Convert.ToDecimal(Session["DollarRate"]), 2);
                    objProductDetailsModel.objProductMaster.OfferPrice = Math.Round(Convert.ToDecimal(objProductDetailsModel.objProductMaster.OfferPrice) * Convert.ToDecimal(Session["DollarRate"]), 2);
                }

                if (objProductDetailsModel.objProductMaster.Images != null)
                {
                    foreach (var item in objProductDetailsModel.objProductMaster.Images)
                    {
                        counter++;
                        if (item.ImagePath != null)
                        {
                            if (!System.IO.File.Exists(Server.MapPath("~/" + item.ImagePath.ToString().Substring(item.ImagePath.ToString().IndexOf("Uploads")))))
                            {
                                item.ImagePath = Request.UrlReferrer.AbsoluteUri.Replace(Request.UrlReferrer.AbsolutePath, "/Content/images/no-product-image.jpg");
                            }
                            else
                            {
                                var tempImagePath = (host + "\\" + item.ImagePath.Substring(item.ImagePath.IndexOf("Uploads"))).Replace(@"\", "/");
                                item.ImagePath = tempImagePath;
                            }
                        }
                        else
                        {
                            item.ImagePath = Request.UrlReferrer.AbsoluteUri.Replace(Request.UrlReferrer.AbsolutePath, "/Content/images/no-product-image.jpg");
                        }

                        if (counter == 1)
                        {
                            objProductDetailsModel.DefaultImagePath = item.ImagePath;
                        }
                    }
                }
            }
            return View(objProductDetailsModel);
        }
    }
}

Asopalav/Views/Shared/_ProductList.cshtml
<div id="breadcrumbs" class="product-margin-top">
    <div class="container">
        <ul>
            <li><a href="@Url.Action("Index","Home")">Home</a></li>
            <li>
                <a href="@Url.Action(ViewData["ProductListPage"].ToString(),"Home",new { @page=ViewData["ProductListPage"].ToString()})">@ViewData["ProductListPage"]</a>
            </li>
        </ul>
    </div>
    <!-- / container -->
</div>
<!-- / body -->
<div id="body">
    <div class="container product-list-top">
        <div class="pagination">
            <ul>
                <li><a href="#"><span class="ico-prev"></span></a></li>
                <li><a href="#">1</a></li>
                <li class="active"><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#"><span class="ico-next"></span></a></li>
            </ul>
        </div>
        <div class="products-wrap">
            <aside id="sidebar">
                <div class="widget">
                    <h3>Products per page:</h3>
                    <form>
                        <div class="checkbox">
                            <label><input type="checkbox" value="">8</label>
                        </div>
                        <div class="checkbox">
                            <label><input type="checkbox" value="">16</label>
                        </div>
                        <div class="checkbox">
                            <label><input type="checkbox" value="">32</label>
                        </div>
                    </form>
                </div>
                <div class="widget">
                    <h3>Sort by:</h3>
                    <form>
                        <div class="checkbox">
                            <label><input type="checkbox" value="">Popularity</label>
                        </div>
                        <div class="checkbox">
                            <label><input type="checkbox" value="">Date</label>
                        </div>
                        <div class="checkbox">
                            <label><input type="checkbox" value="">Price</label>
                        </div>
                    </form>
                </div>
                @*<div class="widget">
                        <h3>Condition:</h3>
                        <form>
                            <div class="checkbox">
                                <label><input type="checkbox" value="">New</label>
                            </div>
                            <div class="checkbox">
                                <label><input type="checkbox" value="">Used</label>
                            </div>
                        </form>
                    </div>*@
                <div class="widget">
                    <h3>Price range:</h3>
                    <fieldset>
                        <div id="price-range"></div>
                    </fieldset>
                </div>
            </aside>
            <div id="content">
                <section class="products">
                    @if (Model.Count != 0)
                    {
                        foreach (var item in Model)
                        {
                    <article>
                        <div class="hovereffect">
                            <img src="@Url.Content(item.ImagePath)" alt="@item.ProductName" width="235" height="275">
                            @*<img src="@Url.Content("~/content/images" + Model.ImageUrl)" />*@
                            <div class="overlay">
                                <h2>@item.ProductCode</h2>
                                <p>
                                    @*<a href="@Url.Action("Index", "ProductDetails", new { id = @Shared.EncriptValue(item.ProductID.ToString()) })">Details</a>*@
                                    @if (!(String.IsNullOrWhiteSpace(item.AmazonUrl)) || !(String.IsNullOrWhiteSpace(item.eBayUrl)))
                                    {
                                        <a href=@(item.AmazonUrl ?? item.eBayUrl) target="_blank">Details</a>
                                    }
                                    else
                                    {
                                        <a href="javascript:void(0);">Not Available</a>
                                    }
                                </p>
                            </div>
                        </div>
                        <h3>@item.ProductName</h3>
                        @*<h4>$@(item.Price.ToString("0.00"))</h4>*@

                        @if ((string)Session["CurrentCurrency"] == "INR")
                        {
                            System.Globalization.CultureInfo ci = new System.Globalization.CultureInfo("en-IN");
                            <h4>@string.Format(ci, "{0:C}", item.Price)</h4>
                        }
                        else
                        {
                            <h4>@string.Format("{0:C}", item.Price)</h4>
                        }
                    </article>
                        }
                    }
                    else
                    {
                        <img src="~/Content/images/no-magento-product-found.jpg" />
                    }
                </section>
            </div>
            <!-- / content -->
        </div>
        @*<div class="pagination">
                <ul>
                    <li><a href="#"><span class="ico-prev"></span></a></li>
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#"><span class="ico-next"></span></a></li>
                </ul>
            </div>*@
    </div>
    <!-- / container -->
</div>
<!-- / body -->